<div class="hero-unit">
    <h1><?php echo sprintf('Welcome to %sCriteria Designer%s', '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo 'This module provide a visual criteria designer for Doctrine ORM 2.'; ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/IADevelop/zf2-criteriadesigner" target="_blank"><?php echo 'Criteria Designer on GitHub'; ?> &raquo;</a></p>
</div>
